-- Create Role Permissions table if it doesn't exist
CREATE TABLE IF NOT EXISTS role_permissions (
    id SERIAL PRIMARY KEY,
    role VARCHAR(50) NOT NULL UNIQUE CHECK (role IN ('SUDO', 'ADMIN', 'RECEPTION', 'PHLEBOTOMY', 'LAB', 'APPROVER')),
    permissions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Delete existing role permissions to reset
DELETE FROM role_permissions;

-- Insert default role permissions
INSERT INTO role_permissions (role, permissions) VALUES
('SUDO', ARRAY[
    'VIEW_RECEPTION', 'CREATE_VISIT', 'COLLECT_DUE_PAYMENT',
    'VIEW_PHLEBOTOMY', 'COLLECT_SAMPLE',
    'VIEW_LAB', 'ENTER_RESULTS',
    'VIEW_APPROVER', 'APPROVE_RESULTS',
    'VIEW_ADMIN_PANEL', 'MANAGE_USERS', 'MANAGE_ROLES', 'MANAGE_TESTS', 'MANAGE_PRICES', 'MANAGE_B2B', 'MANAGE_ANTIBIOTICS',
    'EDIT_APPROVED_REPORT', 'VIEW_AUDIT_LOG'
]),
('ADMIN', ARRAY[
    'VIEW_RECEPTION', 'CREATE_VISIT', 'COLLECT_DUE_PAYMENT',
    'VIEW_PHLEBOTOMY', 'COLLECT_SAMPLE',
    'VIEW_LAB', 'ENTER_RESULTS',
    'VIEW_APPROVER', 'APPROVE_RESULTS',
    'VIEW_ADMIN_PANEL', 'MANAGE_TESTS', 'MANAGE_PRICES', 'MANAGE_B2B', 'MANAGE_ANTIBIOTICS'
]),
('RECEPTION', ARRAY['VIEW_RECEPTION', 'CREATE_VISIT', 'COLLECT_DUE_PAYMENT']),
('PHLEBOTOMY', ARRAY['VIEW_PHLEBOTOMY', 'COLLECT_SAMPLE']),
('LAB', ARRAY['VIEW_LAB', 'ENTER_RESULTS']),
('APPROVER', ARRAY['VIEW_APPROVER', 'APPROVE_RESULTS']);

